# Generated by Django 4.2 on 2023-05-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCBinLoading',
            fields=[
                ('CPCLoadingID', models.AutoField(primary_key=True, serialize=False)),
                ('CPCBin_ID', models.IntegerField()),
                ('Date_of_Load', models.DateTimeField()),
                ('Finish_of_Load', models.DateTimeField()),
                ('Stackable', models.BooleanField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.employee')),
            ],
        ),
    ]
