# Generated by Django 4.2 on 2023-05-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_cpcbinloading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpcbinloading',
            old_name='Employee',
            new_name='employee',
        ),
    ]
