# Generated by Django 4.2 on 2023-05-17 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_rename_employee_cpcbinloading_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpcbinloading',
            name='consignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Application.consignee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PalletLoading',
            fields=[
                ('PalletLoadingID', models.AutoField(primary_key=True, serialize=False)),
                ('Pallet_ID', models.IntegerField()),
                ('Date_of_Load', models.DateTimeField()),
                ('Finish_of_Load', models.DateTimeField()),
                ('Stackable', models.BooleanField()),
                ('Type', models.CharField(max_length=100)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.consignee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.employee')),
            ],
        ),
    ]
